### ISSUE TITLE
首先表示感谢

### ISSUE THREAD

**Issue by lmh77** [SurelySomeday/lmyAutoCheckIn#3]
顺便问问，while true 那最后是不是少个break

**Comment by SurelySomeday** [comment]
可能吧，哈哈，反正能用，关键代码应该没啥问题，逻辑部分可以自己改改

**Comment by lmh77** [comment]
> 可能吧，哈哈，反正能用，关键代码应该没啥问题，逻辑部分可以自己改改

因为没有这个好像，我在ios的pythonista运行会卡掉😂
