### ISSUE TITLE
抛出异常后那个重新执行代码，每次都一抛出线程就停止了

### ISSUE THREAD

**Issue by zimo0825** [SurelySomeday/lmyAutoCheckIn#4]
# 发送检测签到是否开启的请求
def checkIsOpen(userInfo, clazzId):
    try:
        checkOpenUrl = "http://api.mosoteach.cn/mssvc/index.php/checkin/current_open"
        headers = {"Accept-Encoding": "gzip;q=0.7,*;q=0.7",
                   "User-Agent": "Dalvik/2.1.0 (Linux; U; Android 7.1.1; MX6 Build/NMF26O)",
                   "Date": "", "X-device-code": "39285fe4_d165_46d6_a716_d017dd1ad4a4", "X-mssvc-signature": "",
                   "X-mssvc-access-id": userInfo['access_id'], "X-app-id": "MTANDROID", "X-app-version": "3.1.2",
                   "X-mssvc-sec-ts": userInfo['last_sec_update_ts_s'],
                   "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8"}
        checkOpenFormdata = {"clazz_course_id": clazzId}
        headers["Date"] = getDate()
        headers["X-mssvc-signature"] = getSignature(checkOpenUrl, userInfo['user_id'], getDate(),
                                                    userInfo['access_secret'], checkOpenFormdata)
        r = requests.post(checkOpenUrl, headers=headers, data=checkOpenFormdata);
        return r.json()
    except:
        print("checkIsOpen wrong!""异常抛出")
        playsound("music/Je Te Rends Ton Amour.mp3")
        return None

**Comment by lmh77** [comment]
> 
> 
> # 发送检测签到是否开启的请求
> 
> def checkIsOpen(userInfo, clazzId):
> 
>     try:
> 
>         checkOpenUrl = "http://api.mosoteach.cn/mssvc/index.php/checkin/current_open"
> 
>         headers = {"Accept-Encoding": "gzip;q=0.7,*;q=0.7",
> 
>                    "User-Agent": "Dalvik/2.1.0 (Linux; U; Android 7.1.1; MX6 Build/NMF26O)",
> 
>                    "Date": "", "X-device-code": "39285fe4_d165_46d6_a716_d017dd1ad4a4", "X-mssvc-signature": "",
> 
>                    "X-mssvc-access-id": userInfo['access_id'], "X-app-id": "MTANDROID", "X-app-version": "3.1.2",
> 
>                    "X-mssvc-sec-ts": userInfo['last_sec_update_ts_s'],
> 
>                    "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8"}
> 
>         checkOpenFormdata = {"clazz_course_id": clazzId}
> 
>         headers["Date"] = getDate()
> 
>         headers["X-mssvc-signature"] = getSignature(checkOpenUrl, userInfo['user_id'], getDate(),
> 
>                                                     userInfo['access_secret'], checkOpenFormdata)
> 
>         r = requests.post(checkOpenUrl, headers=headers, data=checkOpenFormdata);
> 
>         return r.json()
> 
>     except:
> 
>         print("checkIsOpen wrong!""异常抛出")
> 
>         playsound("music/Je Te Rends Ton Amour.mp3")
> 
>         return None

他代码应该改动了，我用之前的没问题，最新这个确实一直报错

**Comment by zimo0825** [comment]
这个莫得问题我今天发现
