### ISSUE TITLE
可以搞延迟签到吗

### ISSUE THREAD

**Issue by bmcker** [SurelySomeday/lmyAutoCheckIn#5]

**Comment by zimo0825** [comment]
改下time.sleep值就可以了

**Comment by zimo0825** [comment]
msg = checkIsOpen(userInfo, clazz['clazz_id'])
                print('正在检测签到' + "." * count, end='\r')
                if msg != None and msg['result_msg'] == "OK" and clazz['flag'] == 0:
                    # 延时3秒签到
                    time.sleep(3)
                    print("正在签到 " + clazz['clazz_name'])
![image](https://user-images.githubusercontent.com/26477820/78645136-9625e380-78e9-11ea-9985-8a7bab249aa0.png)

**Comment by zimo0825** [comment]
> _没有提供描述。_

加上time.sleep(3)

**Comment by bmcker** [comment]
好的  谢谢大佬

**Comment by zimo0825** [comment]
感觉这个都没得啥子人用




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "bmcker"<notifications@github.com&gt;; 
发送时间: 2020年4月7日(星期二) 晚上10:41
收件人: "SurelySomeday/lmyAutoCheckIn"<lmyAutoCheckIn@noreply.github.com&gt;; 
抄送: "～～"<673087044@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [SurelySomeday/lmyAutoCheckIn] 可以搞延迟签到吗 (#5)





 
好的  谢谢大佬
