### ISSUE TITLE
2020/4/14

### ISSUE THREAD

**Issue by lmh77** [SurelySomeday/lmyAutoCheckIn#6]
😂作者你说没人用，这玩意就是太多人用了，已经有部分人收到蓝墨云的短信，签到行为异常警告了，虽然我还没出现😂😂大家都在琢磨怎么准确时间段执行

**Comment by SurelySomeday** [comment]
😂不是吧，我以为用的不多呢。这个项目可以改成web项目，建一个web页面，访问web页面控制签到的账号和签到的时间。或者用一个定时任务，python3应该有相关的模块。

**Comment by zimo0825** [comment]
我也收到了，3个好有2个收到了，扔服务器24小时执行的，可能是刷新频率太高了

**Comment by zimo0825** [comment]
> 😂作者你说没人用，这玩意就是太多人用了，已经有部分人收到蓝墨云的短信，签到行为异常警告了，虽然我还没出现😂😂大家都在琢磨怎么准确时间段执行

定时执行就没得用了吧，老师签到时间是不固定的，有可能蓝墨是通过接受到的签到数据判断的，和真实的签到发送的请求不一致判断的，这样定时也没得用鸭，太难了上个网课。

**Comment by SurelySomeday** [comment]
知道上课时间的话，可以直接设置具体执行和停止时间，比如从8.00开始执行，9.00停止，中午11.00执行，12：00停止类似这样，再调整一下检查是否有签到的方法的执行频率，应该就好了。代码中有一个检测所有课程是否有签到的方法，应该是检查的代码频率太高了，蓝墨云后端检测到高频率的请求所以被发现了。至于签到，我的方法是根据原来APP里面的签到请求来做的，所以请求的数据是完全一致的，包括请求头，我都做过确认。不过如果蓝墨云官方改变原来的请求接口或者检验用户身份的方法，那么我的程序就完全失效了。

**Comment by zsjlovestudy** [comment]
> 知道上课时间的话，可以直接设置具体执行和停止时间，比如从8.00开始执行，9.00停止，中午11.00执行，12：00停止类似这样，再调整一下检查是否有签到的方法的执行频率，应该就好了。代码中有一个检测所有课程是否有签到的方法，应该是检查的代码频率太高了，蓝墨云后端检测到高频率的请求所以被发现了。至于签到，我的方法是根据原来APP里面的签到请求来做的，所以请求的数据是完全一致的，包括请求头，我都做过确认。不过如果蓝墨云官方改变原来的请求接口或者检验用户身份的方法，那么我的程序就完全失效了。

老哥，麻烦问一下你这个签到是怎么抓包的，我之前写了个UI的看资源的软件，想弄自动签到的软件但是不知道怎么抓包，电脑界面没有签到入口。

**Comment by SurelySomeday** [comment]
不需要抓包了，我代码里面

> > 知道上课时间的话，可以直接设置具体执行和停止时间，比如从8.00开始执行，9.00停止，中午11.00执行，12：00停止类似这样，再调整一下检查是否有签到的方法的执行频率，应该就好了。代码中有一个检测所有课程是否有签到的方法，应该是检查的代码频率太高了，蓝墨云后端检测到高频率的请求所以被发现了。至于签到，我的方法是根据原来APP里面的签到请求来做的，所以请求的数据是完全一致的，包括请求头，我都做过确认。不过如果蓝墨云官方改变原来的请求接口或者检验用户身份的方法，那么我的程序就完全失效了。
> 
> 老哥，麻烦问一下你这个签到是怎么抓包的，我之前写了个UI的看资源的软件，想弄自动签到的软件但是不知道怎么抓包，电脑界面没有签到入口。

不需要抓包了，我代码里面有计算服务器校验的方法，你可以直接生成校验码，根据我代码中的url直接发送相关请求，autoView.py 就是自动查看资源的，你可以自己看一下。根据我的校验方法，你可以改写成java或者其他的，都可以的。

**Comment by zsjlovestudy** [comment]
> 不需要抓包了，我代码里面
> 
> > > 知道上课时间的话，可以直接设置具体执行和停止时间，比如从8.00开始执行，9.00停止，中午11.00执行，12：00停止类似这样，再调整一下检查是否有签到的方法的执行频率，应该就好了。代码中有一个检测所有课程是否有签到的方法，应该是检查的代码频率太高了，蓝墨云后端检测到高频率的请求所以被发现了。至于签到，我的方法是根据原来APP里面的签到请求来做的，所以请求的数据是完全一致的，包括请求头，我都做过确认。不过如果蓝墨云官方改变原来的请求接口或者检验用户身份的方法，那么我的程序就完全失效了。
> > 
> > 
> > 老哥，麻烦问一下你这个签到是怎么抓包的，我之前写了个UI的看资源的软件，想弄自动签到的软件但是不知道怎么抓包，电脑界面没有签到入口。
> 
> 不需要抓包了，我代码里面有计算服务器校验的方法，你可以直接生成校验码，根据我代码中的url直接发送相关请求，autoView.py 就是自动查看资源的，你可以自己看一下。根据我的校验方法，你可以改写成java或者其他的，都可以的。

我是想学一下这个url怎么找到的。。。还有这些效验码，知识盲区了。。

**Comment by SurelySomeday** [comment]
> > 不需要抓包了，我代码里面
> > > > 知道上课时间的话，可以直接设置具体执行和停止时间，比如从8.00开始执行，9.00停止，中午11.00执行，12：00停止类似这样，再调整一下检查是否有签到的方法的执行频率，应该就好了。代码中有一个检测所有课程是否有签到的方法，应该是检查的代码频率太高了，蓝墨云后端检测到高频率的请求所以被发现了。至于签到，我的方法是根据原来APP里面的签到请求来做的，所以请求的数据是完全一致的，包括请求头，我都做过确认。不过如果蓝墨云官方改变原来的请求接口或者检验用户身份的方法，那么我的程序就完全失效了。
> > > 
> > > 
> > > 老哥，麻烦问一下你这个签到是怎么抓包的，我之前写了个UI的看资源的软件，想弄自动签到的软件但是不知道怎么抓包，电脑界面没有签到入口。
> > 
> > 
> > 不需要抓包了，我代码里面有计算服务器校验的方法，你可以直接生成校验码，根据我代码中的url直接发送相关请求，autoView.py 就是自动查看资源的，你可以自己看一下。根据我的校验方法，你可以改写成java或者其他的，都可以的。
> 
> 我是想学一下这个url怎么找到的。。。还有这些效验码，知识盲区了。。

老版本的蓝墨云没有加壳可以直接反编译，我是通过反编译可以拿到APP的混淆后的源代码(方法名和参数全是a,b,c,d这种)，花点时间仔细分析的话，可以得到签到的方法，当然也可以改动源代码(反编译后是smali代码，需要学习一点)。当然，即使现在加了壳，也是有方法反编译的，而且还有动态调式等高级的逆向方法，只不过学习成本比较大，我也只是学了个皮毛。

**Comment by zimo0825** [comment]
> 😂作者你说没人用，这玩意就是太多人用了，已经有部分人收到蓝墨云的短信，签到行为异常警告了，虽然我还没出现😂😂大家都在琢磨怎么准确时间段执行

![image](https://user-images.githubusercontent.com/26477820/79313398-d9f49a80-7f32-11ea-9176-2efe4dfbd842.png)
酷安和妖火都有了就是说挂这么快
